-- Session #1
BEGIN;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT SUM(rating) FROM pizzeria;

SELECT SUM(rating) FROM pizzeria;

COMMIT;

SELECT SUM(rating) FROM pizzeria;
-- Session #2
BEGIN;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

UPDATE pizzeria SET rating = 5 WHERE name = 'Pizza Hut';

COMMIT;

SELECT SUM(rating) FROM pizzeria;